<a href="https://colab.research.google.com/github/firnanda-ra/latihan_data_preprocessing/blob/main/latihan_data_preprocessing_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('dataset.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['Sumber' nan nan]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' nan]


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['Sumber' 38.77777777777778 63777.77777777778]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import  OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])],remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 0.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 0.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 0.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 0.0 1.0 38.77777777777778 63777.77777777778]]


In [ ]:
from operator import le
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1 2]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = 1)

In [ ]:
print(x_train)

[[1.0 0.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 0.0 27.0 48000.0]
 [0.0 0.0 1.0 0.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 0.0 1.0 38.77777777777778 63777.77777777778]
 [0.0 1.0 0.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 0.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 40.0 63777.77777777778]]


In [ ]:
print(y_train)

[1 1 0 0 1 2 0 1]


In [ ]:
print(y_test)

[0 0 1]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [ ]:
print(x_train)

[[1.0 0.0 0.0 -0.3779644730092272 -0.4060397938497913 0.14221361637429802]
 [0.0 0.0 1.0 -0.3779644730092272 -1.8461809345978202 -1.4926454357268726]
 [0.0 0.0 1.0 -0.3779644730092272 -0.15001470216125268 -1.148464582652942]
 [1.0 0.0 0.0 -0.3779644730092272 0.602059004673829 0.5724396827167113]
 [1.0 0.0 0.0 -0.3779644730092272 1.1781154609730407 1.17475617559609]
 [0.0 0.0 0.0 2.6457513110645903 -0.15001470216125268
  -0.13504318193525697]
 [0.0 1.0 0.0 -0.3779644730092272 1.4661436891226463 1.5189370286700206]
 [1.0 0.0 0.0 -0.3779644730092272 -0.694068021999397 -0.632193303042046]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 -0.3779644730092272 -1.4141385923734116 -0.9763741561159767]
 [0.0 0.0 1.0 -0.3779644730092272 -0.26202567977498836
  -0.37405766323659795]
 [0.0 1.0 0.0 -0.3779644730092272 0.026002548374617417
  -0.13504318193525697]]
